import { Theme, ThemeType } from "../ThemeLibrary";

export const gradient: Theme[] = [
  {
    title: "Sunset",
    machineName: "sunset",
    themeConfig: {
      background: "linear-gradient(45deg, #ff9a9e 0%, #fad0c4 100%)",
      foreground: "#fff1f2",
      textColor: "#fff1f2",
      pomodoroPlayIcon: "#fff",
      pomodoroPauseIcon: "#fff",
      pomodoroStopIcon: "#f87171",
      playerBackground: "#783737",
      playerTextColor: "#fff1f2",
      playerLineColor: "#be185d",
      playerControlsColor: "#fff1f2",
      playerModsBgColor: "#e11d48",
      playerModsTextColor: "#fff1f2",
      playerPlayIcon: "#fff",
    },
    type: "gradient",
    colors: ["pink", "lightpink"],
    isAnimated: false,
  },
  {
    title: "Sunrise",
    machineName: "sunrise",
    themeConfig: {
      background:
        "linear-gradient(45deg, rgb(250, 218, 97) 0%, rgb(255, 145, 136) 50%, rgb(255, 90, 205) 100%)",
      foreground: "#fffbea",
      textColor: "#fffbea",
      pomodoroPlayIcon: "#fff",
      pomodoroPauseIcon: "#fff",
      pomodoroStopIcon: "#f87171",
      playerBackground: "#b91c1c",
      playerTextColor: "#fffbea",
      playerLineColor: "#ec3f3f",
      playerControlsColor: "#fffbea",
      playerModsBgColor: "#9e2e2e",
      playerModsTextColor: "#fffbea",
      playerPlayIcon: "#fff",
    },
    type: "gradient",
    colors: ["yellow", "pink"],
    isAnimated: false,
  },
  {
    title: "Nature",
    machineName: "nature",
    themeConfig: {
      background:
        "linear-gradient(45deg, rgb(97, 250, 218) 0%, rgb(136, 255, 145) 50%, rgb(205, 255, 90) 100%)",
      foreground: "#064e3b",
      textColor: "#064e3b",
      pomodoroPlayIcon: "#064e3b",
      pomodoroPauseIcon: "#064e3b",
      pomodoroStopIcon: "#b91c1c",
      playerBackground: "#14532d",
      playerTextColor: "#f0fdf4",
      playerLineColor: "#166534",
      playerControlsColor: "#f0fdf4",
      playerModsBgColor: "#15803d",
      playerModsTextColor: "#f0fdf4",
      playerPlayIcon: "#fff",
    },
    type: "gradient",
    colors: ["cyan", "lime", "lightgreen"],
    isAnimated: false,
  },
  {
    title: "Ocean",
    machineName: "ocean",
    themeConfig: {
      background:
        "linear-gradient(45deg, rgb(97, 218, 250) 0%, rgb(136, 145, 255) 50%, rgb(90, 205, 255) 100%)",
      foreground: "#1e3a8a",
      textColor: "#1e3a8a",
      pomodoroPlayIcon: "#1e3a8a",
      pomodoroPauseIcon: "#1e3a8a",
      pomodoroStopIcon: "#b91c1c",
      playerBackground: "#1e293b",
      playerTextColor: "#f9fafb",
      playerLineColor: "#334155",
      playerControlsColor: "#f9fafb",
      playerModsBgColor: "#3b82f6",
      playerModsTextColor: "#f9fafb",
      playerPlayIcon: "#fff",
    },
    type: "gradient",
    colors: ["lightblue", "blue", "darkblue"],
    isAnimated: false,
  },
  {
    title: "Galaxy",
    machineName: "galaxy",
    themeConfig: {
      background:
        "linear-gradient(45deg, rgb(218, 97, 250) 0%, rgb(145, 136, 255) 50%, rgb(205, 90, 255) 100%)",
      foreground: "#312e81",
      textColor: "#f5f3ff",
      pomodoroPlayIcon: "#f5f3ff",
      pomodoroPauseIcon: "#f5f3ff",
      pomodoroStopIcon: "#ef4444",
      playerBackground: "#1e1b4b",
      playerTextColor: "#f5f3ff",
      playerLineColor: "#4338ca",
      playerControlsColor: "#f5f3ff",
      playerModsBgColor: "#6d28d9",
      playerModsTextColor: "#f5f3ff",
      playerPlayIcon: "#fff",
    },
    type: "gradient",
    colors: ["purple", "blue", "pink"],
    isAnimated: false,
  },
  {
    title: "Aurora",
    machineName: "aurora",
    themeConfig: {
      background: "linear-gradient(45deg, #00c6ff 0%, #0072ff 100%)",
      foreground: "#f0f9ff",
      textColor: "#f0f9ff",
      pomodoroPlayIcon: "#fff",
      pomodoroPauseIcon: "#fff",
      pomodoroStopIcon: "#ef4444",
      playerBackground: "#082f49",
      playerTextColor: "#f0f9ff",
      playerLineColor: "#0369a1",
      playerControlsColor: "#f0f9ff",
      playerModsBgColor: "#0284c7",
      playerModsTextColor: "#f0f9ff",
      playerPlayIcon: "#fff",
    },
    type: "gradient",
    colors: ["cyan", "blue"],
    isAnimated: false,
  },
  {
    title: "Peach",
    machineName: "peach",
    themeConfig: {
      background: "linear-gradient(45deg, #ffecd2 0%, #fcb69f 100%)",
      foreground: "#7c2d12",
      textColor: "#7c2d12",
      pomodoroPlayIcon: "#7c2d12",
      pomodoroPauseIcon: "#7c2d12",
      pomodoroStopIcon: "#b91c1c",
      playerBackground: "#431407",
      playerTextColor: "#fff7ed",
      playerLineColor: "#9a3412",
      playerControlsColor: "#fff7ed",
      playerModsBgColor: "#ea580c",
      playerModsTextColor: "#fff7ed",
      playerPlayIcon: "#fff",
    },
    type: "gradient",
    colors: ["peach", "orange"],
    isAnimated: false,
  },
  {
    title: "Forest",
    machineName: "forest",
    themeConfig: {
      background: "linear-gradient(45deg, #11998e 0%, #38ef7d 100%)",
      foreground: "#064e3b",
      textColor: "#f0fdf4",
      pomodoroPlayIcon: "#f0fdf4",
      pomodoroPauseIcon: "#f0fdf4",
      pomodoroStopIcon: "#ef4444",
      playerBackground: "#022c22",
      playerTextColor: "#f0fdf4",
      playerLineColor: "#065f46",
      playerControlsColor: "#f0fdf4",
      playerModsBgColor: "#047857",
      playerModsTextColor: "#f0fdf4",
      playerPlayIcon: "#fff",
    },
    type: "gradient",
    colors: ["teal", "green"],
    isAnimated: false,
  },
  {
    title: "Berry",
    machineName: "berry",
    themeConfig: {
      background: "linear-gradient(45deg, #ff6a88 0%, #ff99ac 100%)",
      foreground: "#881337",
      textColor: "#fff1f2",
      pomodoroPlayIcon: "#fff",
      pomodoroPauseIcon: "#fff",
      pomodoroStopIcon: "#ef4444",
      playerBackground: "#500724",
      playerTextColor: "#fff1f2",
      playerLineColor: "#9f1239",
      playerControlsColor: "#fff1f2",
      playerModsBgColor: "#be123c",
      playerModsTextColor: "#fff1f2",
      playerPlayIcon: "#fff",
    },
    type: "gradient",
    colors: ["red", "pink"],
    isAnimated: false,
  },
  {
    title: "Midnight",
    machineName: "midnight",
    themeConfig: {
      background: "linear-gradient(45deg, #141e30 0%, #243b55 100%)",
      foreground: "#f9fafb",
      textColor: "#f9fafb",
      pomodoroPlayIcon: "#f9fafb",
      pomodoroPauseIcon: "#f9fafb",
      pomodoroStopIcon: "#ef4444",
      playerBackground: "#0f172a",
      playerTextColor: "#f9fafb",
      playerLineColor: "#1e293b",
      playerControlsColor: "#f9fafb",
      playerModsBgColor: "#334155",
      playerModsTextColor: "#f9fafb",
      playerPlayIcon: "#fff",
    },
    type: "gradient",
    colors: ["darkblue", "navy"],
    isAnimated: false,
  },
  {
    title: "Candy",
    machineName: "candy",
    themeConfig: {
      background: "linear-gradient(45deg, #f6d365 0%, #fda085 100%)",
      foreground: "#7c2d12",
      textColor: "#7c2d12",
      pomodoroPlayIcon: "#7c2d12",
      pomodoroPauseIcon: "#7c2d12",
      pomodoroStopIcon: "#b91c1c",
      playerBackground: "#451a03",
      playerTextColor: "#fff7ed",
      playerLineColor: "#9a3412",
      playerControlsColor: "#fff7ed",
      playerModsBgColor: "#ea580c",
      playerModsTextColor: "#fff7ed",
      playerPlayIcon: "#fff",
    },
    type: "gradient",
    colors: ["yellow", "orange", "pink"],
    isAnimated: false,
  },
  {
    title: "Mint",
    machineName: "mint",
    themeConfig: {
      background: "linear-gradient(45deg, #a1ffce 0%, #faffd1 100%)",
      foreground: "#065f46",
      textColor: "#065f46",
      pomodoroPlayIcon: "#065f46",
      pomodoroPauseIcon: "#065f46",
      pomodoroStopIcon: "#b91c1c",
      playerBackground: "#022c22",
      playerTextColor: "#ecfdf5",
      playerLineColor: "#047857",
      playerControlsColor: "#ecfdf5",
      playerModsBgColor: "#059669",
      playerModsTextColor: "#ecfdf5",
      playerPlayIcon: "#fff",
    },
    type: "gradient",
    colors: ["mint", "lightgreen", "white"],
    isAnimated: false,
  },
];
