import { Theme, ThemeType } from "../ThemeLibrary";

export const solid: Theme[] = [
  {
    title: "Slate",
    machineName: "slate",
    themeConfig: {
      background: "#64748b",
      foreground: "#f1f5f9",
      textColor: "#f1f5f9",
      pomodoroPlayIcon: "#fff",
      pomodoroPauseIcon: "#fff",
      pomodoroStopIcon: "#ef4444",
      playerBackground: "#1e293b",
      playerTextColor: "#f1f5f9",
      playerLineColor: "#334155",
      playerControlsColor: "#f1f5f9",
      playerModsBgColor: "#374151",
      playerModsTextColor: "#f1f5f9",
      playerPlayIcon: "#fff",
    },
    type: "solid",
    colors: ["slate"],
    isAnimated: false,
  },
  {
    title: "Gray",
    machineName: "gray",
    themeConfig: {
      background: "#6b7280",
      foreground: "#f3f4f6",
      textColor: "#f3f4f6",
      pomodoroPlayIcon: "#fff",
      pomodoroPauseIcon: "#fff",
      pomodoroStopIcon: "#ef4444",
      playerBackground: "#111827",
      playerTextColor: "#f3f4f6",
      playerLineColor: "#374151",
      playerControlsColor: "#f3f4f6",
      playerModsBgColor: "#1f2937",
      playerModsTextColor: "#f3f4f6",
      playerPlayIcon: "#fff",
    },
    type: "solid",
    colors: ["gray"],
    isAnimated: false,
  },
  {
    title: "Emerald",
    machineName: "emerald",
    themeConfig: {
      background: "#10b981",
      foreground: "#ecfdf5",
      textColor: "#ecfdf5",
      pomodoroPlayIcon: "#fff",
      pomodoroPauseIcon: "#fff",
      pomodoroStopIcon: "#ef4444",
      playerBackground: "#064e3b",
      playerTextColor: "#ecfdf5",
      playerLineColor: "#065f46",
      playerControlsColor: "#ecfdf5",
      playerModsBgColor: "#047857",
      playerModsTextColor: "#ecfdf5",
      playerPlayIcon: "#fff",
    },
    type: "solid",
    colors: ["emerald"],
    isAnimated: false,
  },
  {
    title: "Blue",
    machineName: "blue",
    themeConfig: {
      background: "#3b82f6",
      foreground: "#eff6ff",
      textColor: "#eff6ff",
      pomodoroPlayIcon: "#fff",
      pomodoroPauseIcon: "#fff",
      pomodoroStopIcon: "#ef4444",
      playerBackground: "#1e3a8a",
      playerTextColor: "#eff6ff",
      playerLineColor: "#1e40af",
      playerControlsColor: "#eff6ff",
      playerModsBgColor: "#1d4ed8",
      playerModsTextColor: "#eff6ff",
      playerPlayIcon: "#fff",
    },
    type: "solid",
    colors: ["blue"],
    isAnimated: false,
  },
  {
    title: "Indigo",
    machineName: "indigo",
    themeConfig: {
      background: "#6366f1",
      foreground: "#eef2ff",
      textColor: "#eef2ff",
      pomodoroPlayIcon: "#fff",
      pomodoroPauseIcon: "#fff",
      pomodoroStopIcon: "#ef4444",
      playerBackground: "#312e81",
      playerTextColor: "#eef2ff",
      playerLineColor: "#3730a3",
      playerControlsColor: "#eef2ff",
      playerModsBgColor: "#4338ca",
      playerModsTextColor: "#eef2ff",
      playerPlayIcon: "#fff",
    },
    type: "solid",
    colors: ["indigo"],
    isAnimated: false,
  },
  {
    title: "Violet",
    machineName: "violet",
    themeConfig: {
      background: "#8b5cf6",
      foreground: "#f5f3ff",
      textColor: "#f5f3ff",
      pomodoroPlayIcon: "#fff",
      pomodoroPauseIcon: "#fff",
      pomodoroStopIcon: "#ef4444",
      playerBackground: "#4c1d95",
      playerTextColor: "#f5f3ff",
      playerLineColor: "#5b21b6",
      playerControlsColor: "#f5f3ff",
      playerModsBgColor: "#6d28d9",
      playerModsTextColor: "#f5f3ff",
      playerPlayIcon: "#fff",
    },
    type: "solid",
    colors: ["violet"],
    isAnimated: false,
  },
  {
    title: "Purple",
    machineName: "purple",
    themeConfig: {
      background: "#a855f7",
      foreground: "#faf5ff",
      textColor: "#faf5ff",
      pomodoroPlayIcon: "#fff",
      pomodoroPauseIcon: "#fff",
      pomodoroStopIcon: "#ef4444",
      playerBackground: "#581c87",
      playerTextColor: "#faf5ff",
      playerLineColor: "#6b21a8",
      playerControlsColor: "#faf5ff",
      playerModsBgColor: "#7e22ce",
      playerModsTextColor: "#faf5ff",
      playerPlayIcon: "#fff",
    },
    type: "solid",
    colors: ["purple"],
    isAnimated: false,
  },
  {
    title: "Fuchsia",
    machineName: "fuchsia",
    themeConfig: {
      background: "#d946ef",
      foreground: "#fdf4ff",
      textColor: "#fdf4ff",
      pomodoroPlayIcon: "#fff",
      pomodoroPauseIcon: "#fff",
      pomodoroStopIcon: "#ef4444",
      playerBackground: "#701a75",
      playerTextColor: "#fdf4ff",
      playerLineColor: "#86198f",
      playerControlsColor: "#fdf4ff",
      playerModsBgColor: "#a21caf",
      playerModsTextColor: "#fdf4ff",
      playerPlayIcon: "#fff",
    },
    type: "solid",
    colors: ["fuchsia"],
    isAnimated: false,
  },
  {
    title: "Pink",
    machineName: "pink",
    themeConfig: {
      background: "#ec4899",
      foreground: "#fdf2f8",
      textColor: "#fdf2f8",
      pomodoroPlayIcon: "#fff",
      pomodoroPauseIcon: "#fff",
      pomodoroStopIcon: "#ef4444",
      playerBackground: "#831843",
      playerTextColor: "#fdf2f8",
      playerLineColor: "#9d174d",
      playerControlsColor: "#fdf2f8",
      playerModsBgColor: "#be185d",
      playerModsTextColor: "#fdf2f8",
      playerPlayIcon: "#fff",
    },
    type: "solid",
    colors: ["pink"],
    isAnimated: false,
  },
  {
    title: "Rose",
    machineName: "rose",
    themeConfig: {
      background: "#f43f5e",
      foreground: "#fff1f2",
      textColor: "#fff1f2",
      pomodoroPlayIcon: "#fff",
      pomodoroPauseIcon: "#fff",
      pomodoroStopIcon: "#ef4444",
      playerBackground: "#881337",
      playerTextColor: "#fff1f2",
      playerLineColor: "#9f1239",
      playerControlsColor: "#fff1f2",
      playerModsBgColor: "#be123c",
      playerModsTextColor: "#fff1f2",
      playerPlayIcon: "#fff",
    },
    type: "solid",
    colors: ["rose"],
    isAnimated: false,
  },
  {
    title: "Red",
    machineName: "red",
    themeConfig: {
      background: "#ef4444",
      foreground: "#fef2f2",
      textColor: "#fef2f2",
      pomodoroPlayIcon: "#fff",
      pomodoroPauseIcon: "#fff",
      pomodoroStopIcon: "#ef4444",
      playerBackground: "#7f1d1d",
      playerTextColor: "#fef2f2",
      playerLineColor: "#991b1b",
      playerControlsColor: "#fef2f2",
      playerModsBgColor: "#b91c1c",
      playerModsTextColor: "#fef2f2",
      playerPlayIcon: "#fff",
    },
    type: "solid",
    colors: ["red"],
    isAnimated: false,
  },
  {
    title: "Orange",
    machineName: "orange",
    themeConfig: {
      background: "#f97316",
      foreground: "#fff7ed",
      textColor: "#fff7ed",
      pomodoroPlayIcon: "#fff",
      pomodoroPauseIcon: "#fff",
      pomodoroStopIcon: "#ef4444",
      playerBackground: "#7c2d12",
      playerTextColor: "#fff7ed",
      playerLineColor: "#9a3412",
      playerControlsColor: "#fff7ed",
      playerModsBgColor: "#c2410c",
      playerModsTextColor: "#fff7ed",
      playerPlayIcon: "#fff",
    },
    type: "solid",
    colors: ["orange"],
    isAnimated: false,
  },
  {
    title: "Amber",
    machineName: "amber",
    themeConfig: {
      background: "#f59e0b",
      foreground: "#fffbeb",
      textColor: "#fffbeb",
      pomodoroPlayIcon: "#fff",
      pomodoroPauseIcon: "#fff",
      pomodoroStopIcon: "#ef4444",
      playerBackground: "#78350f",
      playerTextColor: "#fffbeb",
      playerLineColor: "#92400e",
      playerControlsColor: "#fffbeb",
      playerModsBgColor: "#b45309",
      playerModsTextColor: "#fffbeb",
      playerPlayIcon: "#fff",
    },
    type: "solid",
    colors: ["amber"],
    isAnimated: false,
  },
  {
    title: "Yellow",
    machineName: "yellow",
    themeConfig: {
      background: "#eab308",
      foreground: "#fefce8",
      textColor: "#fefce8",
      pomodoroPlayIcon: "#fff",
      pomodoroPauseIcon: "#fff",
      pomodoroStopIcon: "#ef4444",
      playerBackground: "#713f12",
      playerTextColor: "#fefce8",
      playerLineColor: "#854d0e",
      playerControlsColor: "#fefce8",
      playerModsBgColor: "#a16207",
      playerModsTextColor: "#fefce8",
      playerPlayIcon: "#fff",
    },
    type: "solid",
    colors: ["yellow"],
    isAnimated: false,
  },
  {
    title: "Lime",
    machineName: "lime",
    themeConfig: {
      background: "#84cc16",
      foreground: "#f7fee7",
      textColor: "#f7fee7",
      pomodoroPlayIcon: "#fff",
      pomodoroPauseIcon: "#fff",
      pomodoroStopIcon: "#ef4444",
      playerBackground: "#365314",
      playerTextColor: "#f7fee7",
      playerLineColor: "#3f6212",
      playerControlsColor: "#f7fee7",
      playerModsBgColor: "#4d7c0f",
      playerModsTextColor: "#f7fee7",
      playerPlayIcon: "#fff",
    },
    type: "solid",
    colors: ["lime"],
    isAnimated: false,
  },
  {
    title: "Green",
    machineName: "green",
    themeConfig: {
      background: "#22c55e",
      foreground: "#f0fdf4",
      textColor: "#f0fdf4",
      pomodoroPlayIcon: "#fff",
      pomodoroPauseIcon: "#fff",
      pomodoroStopIcon: "#ef4444",
      playerBackground: "#14532d",
      playerTextColor: "#f0fdf4",
      playerLineColor: "#166534",
      playerControlsColor: "#f0fdf4",
      playerModsBgColor: "#15803d",
      playerModsTextColor: "#f0fdf4",
      playerPlayIcon: "#fff",
    },
    type: "solid",
    colors: ["green"],
    isAnimated: false,
  },
];
