type Track = {
  id: number;
  title: string;
  artist: string;
  url: string;
  type: "calm" | "upbeat";
};

export const tracks: Track[] = [
  {
    id: 1,
    title: "Abroad Again",
    artist: "Jeremy Blake",
    url: "/audio/playlists/calm/Abroad Again - Jeremy Blake.mp3",
    type: "calm",
  },
  {
    id: 2,
    title: "Blind Memories",
    artist: "Cheel",
    url: "/audio/playlists/calm/Blind Memories - Cheel.mp3",
    type: "calm",
  },
  {
    id: 3,
    title: "Blue Dream",
    artist: "Cheel",
    url: "/audio/playlists/calm/Blue Dream - Cheel.mp3",
    type: "calm",
  },
  {
    id: 4,
    title: "Board Games For One",
    artist: "Single Friend",
    url: "/audio/playlists/calm/Board Games For One - Single Friend.mp3",
    type: "calm",
  },
  {
    id: 5,
    title: "Contact High",
    artist: "RKVC",
    url: "/audio/playlists/calm/Contact High - RKVC.mp3",
    type: "calm",
  },
  {
    id: 6,
    title: "Down The Rabbit Hole",
    artist: "The Grey Room and Density & Time",
    url: "/audio/playlists/calm/Down The Rabbit Hole - The Grey Room _ Density & Time.mp3",
    type: "calm",
  },
  {
    id: 7,
    title: "Drop Of A Hat",
    artist: "The Grey Room and Density & Time",
    url: "/audio/playlists/calm/Drop Of A Hat - The Grey Room _ Density & Time.mp3",
    type: "calm",
  },
  {
    id: 8,
    title: "Drown Me Out",
    artist: "VYEN",
    url: "/audio/playlists/calm/Drown Me Out - VYEN.mp3",
    type: "calm",
  },
  {
    id: 9,
    title: "Kicking It",
    artist: "Dyalla",
    url: "/audio/playlists/calm/Kicking It - Dyalla.mp3",
    type: "calm",
  },
  {
    id: 10,
    title: "Lazy Walk",
    artist: "Cheel",
    url: "/audio/playlists/calm/Lazy Walk - Cheel.mp3",
    type: "calm",
  },
  {
    id: 11,
    title: "Manhattan",
    artist: "Dyalla",
    url: "/audio/playlists/calm/Manhattan - Dyalla.mp3",
    type: "calm",
  },
  {
    id: 12,
    title: "Misdirection",
    artist: "The Grey Room and Density & Time",
    url: "/audio/playlists/calm/Misdirection - The Grey Room _ Density & Time.mp3",
    type: "calm",
  },
  {
    id: 13,
    title: "Never Play",
    artist: "Jeremy Blake",
    url: "/audio/playlists/calm/Never Play - Jeremy Blake.mp3",
    type: "calm",
  },
  {
    id: 14,
    title: "Never Surrender",
    artist: "Anno Domini Beats",
    url: "/audio/playlists/calm/Never Surrender - Anno Domini Beats.mp3",
    type: "calm",
  },
  {
    id: 15,
    title: "No Rush",
    artist: "Dyalla",
    url: "/audio/playlists/calm/No Rush - Dyalla.mp3",
    type: "calm",
  },
  {
    id: 16,
    title: "On The Flip",
    artist: "The Grey Room and Density & Time",
    url: "/audio/playlists/calm/On The Flip - The Grey Room _ Density & Time.mp3",
    type: "calm",
  },
  {
    id: 17,
    title: "Papov",
    artist: "Papov",
    url: "/audio/playlists/calm/Papov - Yung Logos.mp3",
    type: "calm",
  },
  {
    id: 18,
    title: "Simple",
    artist: "Patrick Patrikios",
    url: "/audio/playlists/calm/Simple - Patrick Patrikios.mp3",
    type: "calm",
  },
  {
    id: 19,
    title: "State Drive",
    artist: "VYEN",
    url: "/audio/playlists/calm/State Drive - VYEN.mp3",
    type: "calm",
  },
  {
    id: 20,
    title: "Sunset n Beachz",
    artist: "Ofshane",
    url: "/audio/playlists/calm/Sunset n Beachz - Ofshane.mp3",
    type: "calm",
  },
  {
    id: 21,
    title: "TrueArtRealAffectionPart4",
    artist: "Noir Et Blanc Vie",
    url: "/audio/playlists/calm/TrueArtRealAffectionPart4 - Noir Et Blanc Vie.mp3",
    type: "calm",
  },

  // upbeat tracks
  {
    id: 22,
    title: "368",
    artist: "Dyalla",
    url: "/audio/playlists/upbeat/368 - Dyalla.mp3",
    type: "upbeat",
  },
  {
    id: 23,
    title: "A Stroll",
    artist: "The Grey Room and Density & Time",
    url: "/audio/playlists/upbeat/A Stroll - The Grey Room _ Density & Time.mp3",
    type: "upbeat",
  },
  {
    id: 24,
    title: "A Truly Dazzling Dream",
    artist: "National Sweetheart",
    url: "/audio/playlists/upbeat/A Truly Dazzling Dream - National Sweetheart.mp3",
    type: "upbeat",
  },
  {
    id: 25,
    title: "Benji",
    artist: "Dyalla",
    url: "/audio/playlists/upbeat/Benji - Dyalla.mp3",
    type: "upbeat",
  },
  {
    id: 26,
    title: "Bodega Cat",
    artist: "Dyalla",
    url: "/audio/playlists/upbeat/Bodega Cat - Dyalla.mp3",
    type: "upbeat",
  },
  {
    id: 27,
    title: "Floating On Fire",
    artist: "The Grey Room and Density & Time",
    url: "/audio/playlists/upbeat/Floating On Fire - The Grey Room _ Density & Time.mp3",
    type: "upbeat",
  },
  {
    id: 28,
    title: "Hey There",
    artist: "half.cool",
    url: "/audio/playlists/upbeat/Hey There - half.cool.mp3",
    type: "upbeat",
  },
  {
    id: 29,
    title: "Indecision",
    artist: "Dyalla",
    url: "/audio/playlists/upbeat/Indecision - Dyalla.mp3",
    type: "upbeat",
  },
  {
    id: 30,
    title: "Lawrence",
    artist: "TrackTribe",
    url: "/audio/playlists/upbeat/Lawrence - TrackTribe.mp3",
    type: "upbeat",
  },
  {
    id: 31,
    title: "Like It Loud",
    artist: "Dyalla",
    url: "/audio/playlists/upbeat/Like It Loud - Dyalla.mp3",

    type: "upbeat",
  },
  {
    id: 32,
    title: "MydNyte",
    artist: "Noir Et Blanc Vie",
    url: "/audio/playlists/upbeat/MydNyte - Noir Et Blanc Vie.mp3",
    type: "upbeat",
  },
  {
    id: 33,

    title: "Organic Guitar House",
    artist: "Dyalla",
    url: "/audio/playlists/upbeat/Organic Guitar House - Dyalla.mp3",
    type: "upbeat",
  },
  {
    id: 34,
    title: "Patience",
    artist: "Dyalla",
    url: "/audio/playlists/upbeat/Patience - Dyalla.mp3",
    type: "upbeat",
  },
  {
    id: 35,
    title: "Poolside Radio",
    artist: "Dyalla",
    url: "/audio/playlists/upbeat/Poolside Radio - Dyalla.mp3",
    type: "upbeat",
  },
  {
    id: 36,
    title: "Puppy Love",
    artist: "Jeremy Blake",

    url: "/audio/playlists/upbeat/Puppy Love - Jeremy Blake.mp3",
    type: "upbeat",
  },

  {
    id: 37,
    title: "Spatial Entaglement",
    artist: "The Grey Room and Density & Time",
    url: "/audio/playlists/upbeat/Spatial Entaglement - The Grey Room _ Density & Time.mp3",
    type: "upbeat",
  },
  {
    id: 38,
    title: "Sunset Dream",
    artist: "Cheel",
    url: "/audio/playlists/upbeat/Sunset Dream - Cheel.mp3",
    type: "upbeat",
  },
  {
    id: 39,
    title: "The Last Oasis",
    artist: "The Grey Room and Density & Time",
    url: "/audio/playlists/upbeat/The Last Oasis - The Grey Room _ Density & Time.mp3",
    type: "upbeat",
  },
  {
    id: 40,
    title: "Top Ten",
    artist: "Jeremy Blake",
    url: "/audio/playlists/upbeat/Top Ten - Jeremy Blake.mp3",
    type: "upbeat",
  },
  {
    id: 41,
    title: "Treat Yourself",
    artist: "Dyalla",
    url: "/audio/playlists/upbeat/Treat Yourself - Dyalla.mp3",
    type: "upbeat",
  },
  {
    id: 42,
    title: "Window Shopping",
    artist: "Jeremy Black",
    url: "/audio/playlists/upbeat/Window Shopping - Jeremy Black.mp3",
    type: "upbeat",
  },
];
